### PR TITLE
add capability to select all with one click

### PR DESCRIPTION
**Pull request by Jey-Cee**

### CODE REVIEW

**Comment by julianlam** [comment]
Does this affect the ability to select a portion of the text via click-drag?

**Comment by Jey-Cee** [comment]
no but it effects only text in code tags

**Comment by julianlam** [comment]
That's what I mean, does it affect ability to select partial text in code blocks...

**Comment by julianlam** [comment]
Yeah I can't merge this, I am no longer able to select a single line or word easily.

**Pull request closed without merging**
