### PR TITLE
Feat: ES6 & dependencies update

### PR DESCRIPTION
**Pull request by Antosik**
**Done**:
- `index.js` and `websockets.js` updated to ES6 (async/await, let/const, etc.)
- Dependencies update
  - markdown-it `10.0.0 -> 12.0.6` ([changelog](https://github.com/markdown-it/markdown-it/blob/master/CHANGELOG.md))
  - misc dev dependencies
- Removed `async` dependency (because `websockets.js` don't use it anymore)
- Added `settingsRoute` in `plugin.json` to display a cool "Settings" button in plugins list

### CODE REVIEW

**Comment by Antosik** [comment]
Current questions:
- Do we need to update client-side hooks to a new `hooks` module? (I also have [a question](https://community.nodebb.org/post/83478) about it)
- Do we need to remove one of the lock files? (`package.json` or `yarn.lock`)

I also want to add an ability to set the size of images out-of-box by using the [markdown-it-imsize](https://github.com/tatsy/), but this package is a bit out of date :c

**Comment by julianlam** [comment]
Wow, good lord, nice work!

You can update the hooks to use client-side hooks, yes. It is backwards compatible in that action hooks when fired will still fire the older `$(window).trigger(evtName, parameters);` function... and will continue to do so until v2, I guess.

Let's do that in a separate commit :smile:

**Comment by julianlam** [comment]
Will publish a new version after your commit to update client-side hooks.

**Comment by julianlam** [comment]
> Do we need to remove one of the lock files? (package.json or yarn.lock)

Probably both are superfluous, but I prefer `yarn.lock`, so I'll remove the other.

**Comment by Antosik** [comment]
@julianlam, hmm
Looks like currently, I can't implement the client-side hooks 🤔
`action:topic.loaded`, `action:posts.loaded`, `action:posts.edited`, and `action:composer.preview` hooks still firing via $(window).trigger :c

**Comment by julianlam** [comment]
@Antosik Here you go :smile:

**Pull request merged**
