### PR TITLE
adding a dir attr to each token 

### PR DESCRIPTION
**Pull request by akhoury**
along with adding support for many attr on tokens for custom css support
related to https://github.com/NodeBB/nodebb-plugin-composer-default/issues/121

This does not include composer "buttons" yet, this is merely auto-fixing the direction of each token, and allowing advanced attrs to be used for css styles using https://www.npmjs.com/package/markdown-it-attrs

### CODE REVIEW

**Comment by julianlam** [comment]
8.10.0

**Comment by BenLubar** [comment]
@julianlam this creates invalid HTML

```
<div class="content" component="post/content" itemprop="text">
	<p dir="auto">Here are some three-letter words:</p dir="auto">
<ul dir="auto">
<li dir="auto">ebb</li dir="auto">
<li dir="auto">apt</li dir="auto">
<li dir="auto">ask</li dir="auto">
<li dir="auto">its</li dir="auto">
<li dir="auto">egg</li dir="auto">
<li dir="auto">job</li dir="auto">
</ul dir="auto">

</div>
```

**Comment by julianlam** [comment]
@akhoury can we limit this to paragraph elements, maybe?

**Comment by BenLubar** [comment]
More importantly, can we limit this to *starting* tags so it's valid HTML?

**Comment by akhoury** [comment]
yeesh

**Comment by akhoury** [comment]
new [PR](https://github.com/julianlam/nodebb-plugin-markdown/pull/107) submitted

**Comment by julianlam** [comment]
Thanks for the catch @BenLubar and the quick fix @akhoury

**Pull request merged**
